-- Migration: V4 - Criação da tabela de produtos (controle de estoque)

CREATE TABLE produtos (
    id_produto      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150) NOT NULL,
    categoria       VARCHAR(20)  NOT NULL,
    estoque_atual   INT          NOT NULL,
    estoque_minimo  INT          NOT NULL,
    unidade_medida  VARCHAR(20)  NOT NULL,
    data_cadastro   DATE         NOT NULL,
    CONSTRAINT uk_produtos_nome UNIQUE (nome),
    CONSTRAINT ck_produtos_estoque_atual CHECK (estoque_atual >= 0),
    CONSTRAINT ck_produtos_estoque_minimo CHECK (estoque_minimo >= 0)
);

CREATE INDEX idx_produtos_categoria ON produtos(categoria);
